### **NumPy相关函数的操作示例**

In [1]:
# -*- coding:utf-8 -*-
import cv2 as cv
import numpy as np
import sys
import datetime
rootpath = '/home/zomnk/python_ws/02-OpenCV4/images/'

#### 创建ndarray对象

In [2]:
# 使用np.array()创建一个5*5,数据类型为float32的对象(即矩阵)
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]], dtype='float32')
# 使用np.ones()创建一个5*5,数据类型为uint8的全1对象
b = np.ones((5,5), dtype='uint8')
# 使用np.zeros()创建一个5*5,数据类型为float32的全0对象
c = np.zeros((5,5), dtype='float32')
print('创建对象(np.array): \n{}'.format(a))
print('创建对象(np.ones): \n{}'.format(b))
print('创建对象(np.zeros): \n{}'.format(c))

创建对象(np.array): 
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]
创建对象(np.ones): 
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
创建对象(np.zeros): 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### ndarray对象切片和索引

In [9]:
image = cv.imread(rootpath + 'flower.jpg')
# 读取图像，并判断图像是否读取成功
if image is None:
    print('Failed to read flowers.jpg')
    sys.exit
# 创建灰度图对象
gray = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
# 读取图像位于(45,45)处的像素值
print('位于(45,45)处的像素值为: {}'.format(gray[45,45]))

位于(45,45)处的像素值为: 235
(442, 442, 3)


In [10]:
# 裁减部分图像(灰度图像和RGB图像)
res_gray = gray[30:260, 50:350]
res_color1 = image[30:260, 50:350, :]
res_color2 = image[100:220, 80:220, :]
# 进行通道分离
b = image[:, :, 0]
g = image[:, :, 1]
r = image[:, :, 2]
# 展示裁减和分离通道的结果
cv.imshow('Result crop gray',res_gray)
cv.imshow('Result crop color1',res_color1)
cv.imshow('Result crop color2',res_color2)
cv.imshow('Result split b',b)
cv.imshow('Result split g',g)
cv.imshow('Result split r',r)


# 等待按键按下
cv.waitKey(0);
# 结束所有窗口
cv.destroyAllWindows()

#### 生成随机数

In [15]:
# 生成一个5*5,取值范围为0~100的数组
values1 = np.random.randint(0, 100, (5,5), dtype='uint8')
# 生成一个2*3、元素服从均值为0,标准差为1的正态分布的数组
values2 = np.random.randn(2, 3)
print('生成随机数(np.random.randint): \n{}'.format(values1))
print('生成随机数(np.random.randn): \n{}'.format(values2))

生成随机数(np.random.randint): 
[[ 7 15 15 50 98]
 [76 87  4 58 70]
 [13 90 54 49 75]
 [85 43 83  5 41]
 [21 31 53 85 18]]
生成随机数(np.random.randn): 
[[-0.17828999  0.08079913 -1.27946203]
 [ 1.62711765  2.17181913 -1.01341918]]
