### **寻找矩阵的最值**

In [1]:
# -*- coding:utf-8 -*-
import cv2 as cv
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

rootpath = '/home/zomnk/python_ws/02-OpenCV4/images/'

In [2]:
# 新建array
array = np.array([1, 2, 3, 4, 5, 10, 6, 7, 8, 9, 10, 0])
# 将array调整为维度为3*4的单通道图像
img1 = array.reshape((3, 4))
print(img1)
minval_1, maxval_1, minloc_1, maxloc_1 = cv.minMaxLoc(img1)
print('图像img1中的最小值为%s, 其位置为%s' % (minval_1, minloc_1))
print('图像img1中的最大值为%s, 其位置为%s' % (maxval_1, maxloc_1))

[[ 1  2  3  4]
 [ 5 10  6  7]
 [ 8  9 10  0]]
图像img1中的最小值为0.0, 其位置为(3, 2)
图像img1中的最大值为10.0, 其位置为(1, 1)


In [3]:
# 将array重塑为3*2*2的多通道图像
img2 = array.reshape((3, 2, 2))
# 先将多通道图像重塑
img2_re = img2.reshape(1, -1)
print(img2_re)
minval_2, maxval_2, minloc_2, maxloc_2 = cv.minMaxLoc(img2_re)
print('图像img2中的最小值为%s, 其位置为%s' % (minval_2, minloc_2))
print('图像img2中的最大值为%s, 其位置为%s' % (maxval_2, maxloc_2))

[[ 1  2  3  4  5 10  6  7  8  9 10  0]]
图像img2中的最小值为0.0, 其位置为(11, 0)
图像img2中的最大值为10.0, 其位置为(5, 0)
