### **计算图像的均值和标准差**

In [1]:
# -*- coding:utf-8 -*-
import cv2 as cv
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

rootpath = '/home/zomnk/python_ws/02-OpenCV4/images/'

In [2]:
# 新建array
array = np.array([1, 2, 3, 4, 5, 10, 6, 7, 8, 9, 10, 0])
# 将array调整为维度为3*4的单通道图像
img1 = array.reshape((3, 4))
# 将array重塑为3*2*2的多通道图像
img2 = array.reshape((3, 2, 2))
print(img1, img2)

[[ 1  2  3  4]
 [ 5 10  6  7]
 [ 8  9 10  0]] [[[ 1  2]
  [ 3  4]]

 [[ 5 10]
  [ 6  7]]

 [[ 8  9]
  [10  0]]]


In [3]:
# 分别计算图像img1和img2的均值和标准差
mean_img1 = cv.mean(img1)
mean_img2 = cv.mean(img2)
mean_std_dev_img1 = cv.meanStdDev(img1)
mean_std_dev_img2 = cv.meanStdDev(img2)

In [4]:
# 输出cv.mean()函数的计算结果
print('cv.mean()函数计算结果如下：')
print('图像img1的均值为{}'.format(mean_img1))
print('图像img2的均值为{}, \n其中第1个通道的均值为{}, \n第二个通道的均值为{}'.format(mean_img2, mean_img2[0], mean_img2[1]))

cv.mean()函数计算结果如下：
图像img1的均值为(5.416666666666666, 0.0, 0.0, 0.0)
图像img2的均值为(5.5, 5.333333333333333, 0.0, 0.0), 
其中第1个通道的均值为5.5, 
第二个通道的均值为5.333333333333333


In [5]:
# 输出cv.meanStdDev()函数的计算结果
print('cv.meanStdDev()函数的计算结果如下：')
print('图像img1的均值为{}, \n标准差为{}'.format(mean_img1[0], float(mean_std_dev_img1[1])))
print('图像img2的均值为{}, \n其中第1个通道的均值为{}, \n 第2个通道的均值为{}\n'
      '标准差为{}, \n其中第1个通道的标准差为{}, \n第2个通道的标准差为{}'.format(mean_img2, mean_img2[0], mean_img2[1], mean_std_dev_img2[1], float(mean_std_dev_img2[1][0]), float(mean_std_dev_img2[1][1])))

cv.meanStdDev()函数的计算结果如下：
图像img1的均值为5.416666666666666, 
标准差为3.32812092461931
图像img2的均值为(5.5, 5.333333333333333, 0.0, 0.0), 
其中第1个通道的均值为5.5, 
 第2个通道的均值为5.333333333333333
标准差为[[2.98607881]
 [3.63623737]], 
其中第1个通道的标准差为2.9860788111948193, 
第2个通道的标准差为3.636237371545238
