### **生成边缘检测滤波器**

有时我们需要得到提取图像边缘的滤波器，并修改滤波器以提升边缘检测的效果

第1和第2个参数决定边缘提取效果，第3个参数如果取1，3，5，7，则生成的边缘检测算子就是Sobel算子，如果取cv.FILTER_SCHARR,则生成的是Scharr算子

In [9]:
# -*- coding:utf-8 -*-
import cv2 as cv
import numpy as np
import sys
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
# 设置中文字体
matplotlib.rcParams['font.family'] = 'simhei'
matplotlib.rcParams['axes.unicode_minus'] = False
rootpath = '/home/zomnk/python_ws/02-OpenCV4/images/'

In [10]:
# 一阶x方向的Sobel算子
sobel_x1, sobel_y1 = cv.getDerivKernels(1, 0, 3)
sobel_X1 = sobel_y1 * sobel_x1.T
print('一阶x方向的Sobel算子为：\n{}'.format(sobel_X1))

一阶x方向的Sobel算子为：
[[-1.  0.  1.]
 [-2.  0.  2.]
 [-1.  0.  1.]]


In [11]:
# 二阶x方向的Sobel算子
sobel_x2, sobel_y2 = cv.getDerivKernels(2, 0, 5)
sobel_X2 = sobel_y2 * sobel_x2.T
print('二阶x方向的Sobel算子为：\n{}'.format(sobel_X2))

二阶x方向的Sobel算子为：
[[  1.   0.  -2.   0.   1.]
 [  4.   0.  -8.   0.   4.]
 [  6.   0. -12.   0.   6.]
 [  4.   0.  -8.   0.   4.]
 [  1.   0.  -2.   0.   1.]]


In [12]:
# 三阶x方向的Sobel算子
sobel_x3, sobel_y3 = cv.getDerivKernels(3, 0, 7)
sobel_X3 = sobel_y3 * sobel_x3.T
print('三阶x方向的Sobel算子为：\n{}'.format(sobel_X3))

三阶x方向的Sobel算子为：
[[ -1.   0.   3.   0.  -3.   0.   1.]
 [ -6.   0.  18.   0. -18.   0.   6.]
 [-15.   0.  45.   0. -45.   0.  15.]
 [-20.   0.  60.   0. -60.   0.  20.]
 [-15.   0.  45.   0. -45.   0.  15.]
 [ -6.   0.  18.   0. -18.   0.   6.]
 [ -1.   0.   3.   0.  -3.   0.   1.]]


In [13]:
# x方向的Schaar算子
sobel_x, sobel_y = cv.getDerivKernels(1, 0, cv.FILTER_SCHARR)
sobel_X = sobel_y * sobel_x.T
print('x方向的Schaar算子为：\n{}'.format(sobel_X))

x方向的Schaar算子为：
[[ -3.   0.   3.]
 [-10.   0.  10.]
 [ -3.   0.   3.]]
