### **卷积模板旋转180度**

如果卷积模板不是中心对称的，使用cv.flip()函数可以旋转180度

In [4]:
# -*- coding:utf-8 -*-
import cv2 as cv
import numpy as np
import sys
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
# 设置中文字体
matplotlib.rcParams['font.family'] = 'simhei'
matplotlib.rcParams['axes.unicode_minus'] = False
rootpath = '/home/zomnk/python_ws/02-OpenCV4/images/'

In [ ]:
src = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]], dtype='float32')
kernel1 = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]], dtype='float32') / 9
# 卷积模版旋转180度
result = cv.flip(src, -1) 
print('原卷积模板为：\n{}'.format(src))
print('旋转180°后的卷积模板为：\n{}'.format(result))

原卷积模板为：
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]
旋转180°后的卷积模板为：
[[25. 24. 23. 22. 21.]
 [20. 19. 18. 17. 16.]
 [15. 14. 13. 12. 11.]
 [10.  9.  8.  7.  6.]
 [ 5.  4.  3.  2.  1.]]
